# Generated by Django 5.2 on 2025-05-13 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorynotes',
            options={'verbose_name_plural': 'Note Category'},
        ),
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name_plural': 'Notes'},
        ),
    ]
