# Generated by Django 5.2 on 2025-05-20 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorynotes',
            old_name='category_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='note_title',
            new_name='title',
        ),
    ]
