# Generated by Django 5.2 on 2025-05-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_rename_category_title_categorynotes_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorynotes',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
