# Generated by Django 5.2 on 2025-05-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_alter_categorynotes_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorynotes',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
