# Generated by Django 5.2 on 2025-06-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_alter_categorynotes_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='note_text',
            field=models.TextField(),
        ),
    ]
