# Generated by Django 5.2 on 2025-07-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_alter_notes_note_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorynotes',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
