# Generated by Django 5.2 on 2025-07-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0007_alter_categorynotes_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorynotes',
            name='title',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
