# Generated by Django 5.2 on 2025-09-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0003_ocrfileupload_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrfileupload',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
