# Generated by Django 5.2 on 2025-09-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0004_alter_ocrfileupload_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrfileupload',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
