# Generated by Django 5.2 on 2025-09-23 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0005_alter_ocrfileupload_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ocrfileupload',
            options={'verbose_name_plural': 'OCR File Upload'},
        ),
    ]
